info: |
    Show a graph with directed connections. The nodes are movable.

valid_names:
    - source
    - target
    - type

name_comments: |
    "source" is the beginning of the arrow
    "target" is the end of the arrow
    "type" is the type of arrow (color)

scripts:
    - d3.min.js

styles:
    - main.css

default_parameters: {
    width: 800,
    height: 800,
}

require_packages:
    - df2json

require_server: false

original_url: http://bl.ocks.org/mbostock/1153292
